# Site settings
title: Ligue des Vidéastes Extraordinaires
header-img: img/home-bg.jpg
email: info@racheletmichel.com
description: "Il s'agit de chercher ce qu'on peut partager comme information pertinente au domaine de la vidéo sur le web!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://racheletmichel.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
