# Site settings
title: Michel de Silva chante Michel de Silva
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Il s'agit de chercher ce qu'on peut offrir d'information!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
